apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-config
  namespace: user-pipelines
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: gitlab-secretstore
    kind: SecretStore
  target:
    name: docker-config
  data:
  - secretKey: config.json
    remoteRef:
      key: gitlab/dockerconfig
      property: config.json
