apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-ssh-credentials
  namespace: user-pipelines
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: gitlab-secretstore
    kind: SecretStore
  target:
    name: gitlab-ssh-credentials
  data:
  - secretKey: id_rsa
    remoteRef:
      key: gitlab/ssh-credentials
      property: id_rsa
  - secretKey: known_hosts
    remoteRef:
      key: gitlab/ssh-credentials
      property: known_hosts
  