apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace-user-pipelines.yaml
- pvc-maven-repository.yaml
- pvc-source.yaml
- rbac-tekton-pipelines-access.yaml
- secretstore.yaml
- external-gitlab-ssh-credentials.yaml
- external-docker-config.yaml
- external-argo-auth.yaml
- argo-server-config.yaml
namespace: user-pipelines
