apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gitlab-secretstore
  namespace: user-pipelines
spec:
  provider:
    vault:
      server: "https://vault.192-168-3-196.nip.io"
      # base64 vault ca cert 
      caBundle: "LS0tLS1..."
      path: "webhook"
      version: "v1"
      auth:
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "dev"
          # A required field containing the Vault Role to assume.
          role: "gitlab-ssh-credentials"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: "gitlab-ssh-credentials"