apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-access
  namespace: argo-events
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: webhook-secretstore
    kind: SecretStore
  target:
    name: gitlab-access
  data:
  - secretKey: access-token
    remoteRef:
      key: gitlab/token
      property: access-token
  - secretKey: secret-token
    remoteRef:
      key: gitlab/token
      property: secret-token
  
