apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-cert
  namespace: argo-events
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: webhook-secretstore
    kind: SecretStore
  target:
    name: gitlab-cert
  data:
  - secretKey: ca-cert
    remoteRef:
      key: gitlab/cert
      property: ca-cert
  
